theme: jekyll-theme-minimal
title: IBM Embedded Business AI Framework
description: Explore a new way to craft A.I. solutions using a modern approach to machine reasoning.
google_analytics: UA-122581302-1
plugins:
  - jekyll-seo-tag
#show_downloads: true
#logo: https://avatars2.githubusercontent.com/u/40904555?s=200&v=4
